[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "monitoring-system"
version = "0.1.0"
authors = [
    { name = "Tu Nombre", email = "tu@email.com" },
]
description = "Sistema de Monitoreo"
requires-python = ">=3.8" 